### ISSUE TITLE
Any interest in an OS X PR?

### ISSUE THREAD

**Issue by jimmoores** [EtchedPixels/Virtual68#1]
Hi,

I've been keeping an eye on FUZIX since the project started and wanted to have a play - so I tried Virtual68 but ran into build issues on my old MacBook Pro.  I put together a small change based on some #ifdef __MACH__ in the v68.c file.  Is there any interest in me creating a PR?  I'm happy to refactor it if necessary, or if there's no interest, I'll just sit on it.

Best Regards,

Jim

**Comment by EtchedPixels** [comment]
If you could yes, unless its horribly ugly it's sensible to merge I think

**Comment by EtchedPixels** [comment]
Thanks for the patch. I'll re-arrange it a bit for neatness I think when I get time, and then apply.
